In [15]:
import pandas as pd

In [16]:
img_metadata_path = '../data/cropped_image_metadata.csv'
target_metadata_path = '../data/Fracture_Type.csv'
sbf_view_path = '../data/unnamed_views_sbf_export.csv'

model_img_data_path = '../data/model_images.csv'
model_trg_data_path = '../data/model_targets.csv'

In [17]:
df_img = pd.read_csv(img_metadata_path)
df_trg = pd.read_csv(target_metadata_path)
df_sbf = pd.read_csv(sbf_view_path).rename(columns = {'STD_VIEW': 'view_std_sbf', 'FILENAME_VIEW': 'view'})

In [18]:
df_img

,external_id,bbox_top,bbox_left,bbox_height,bbox_width,note,poor_quality,not_a_phf_view,brightness_flipped,PATIENT_ID,...,FILENAME_VIEW,MIN,MAX,DATA_TYPE,WIDTH,HEIGHT,NUM_CHANNELS,ROI,JPG_PATH,CROPPED_IMAGE_PATH
0,AN00001_Y_VIEW_4,401.0,505.0,996.0,863.0,NaN,False,False,False,AN00001,...,Y_VIEW_4,1139,26177,int16,2328,2928,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,../data/cropped_images/AN00001_Y_VIEW_4.jpg
1,AN00010__1001,277.0,688.0,631.0,393.0,NaN,False,False,False,AN00010,...,_1001,5398,16383,int16,2142,1855,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,../data/cropped_images/AN00010__1001.jpg
2,AN00010__1002,1098.0,642.0,844.0,825.0,"bad quality image, drop",True,False,False,AN00010,...,_1002,6035,11921,int16,2119,2300,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,NaN
3,AN00010__1004,809.0,353.0,347.0,409.0,"not the shoulder, drop",False,True,False,AN00010,...,_1004,4875,16383,int16,1571,2499,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,NaN
4,AN00010__1005,693.0,1087.0,349.0,389.0,"Not shoulder, skip",False,True,False,AN00010,...,_1005,0,16383,int16,2630,1477,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111,AN00099_Shoulder_R_2,588.0,813.0,532.0,454.0,NaN,False,False,False,AN00099,...,Shoulder_R_2,0,30823,int16,2931,1614,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,../data/cropped_images/AN00099_Shoulder_R_2.jpg
1112,AN00099_Shoulder_R_3,69.0,1491.0,521.0,455.0,NaN,False,False,False,AN00099,...,Shoulder_R_3,0,29055,int16,2163,1022,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,../data/cropped_images/AN00099_Shoulder_R_3.jpg
1113,AN00001_AXILLARY_3,1363.0,1834.0,726.0,698.0,NaN,False,False,True,AN00001,...,AXILLARY_3,10244,26573,int16,2928,2328,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,../data/cropped_images/AN00001_AXILLARY_3.jpg
1114,AN00001_EXT_ROTATION_2,726.0,677.0,796.0,721.0,NaN,False,False,True,AN00001,...,EXT_ROTATION_2,1421,27093,int16,2928,2328,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,../data/cropped_images/AN00001_EXT_ROTATION_2.jpg
1115,AN00001_INT_ROTATION_1,754.0,626.0,693.0,660.0,NaN,False,False,True,AN00001,...,INT_ROTATION_1,2272,27356,int16,2928,2328,1,False,/home/xiaofey/xray/xray-master/data/exported_j...,../data/cropped_images/AN00001_INT_ROTATION_1.jpg

In [19]:
# clean image data
df_img = df_img.dropna(subset='CROPPED_IMAGE_PATH')
df_img = df_img.rename(columns = {'CROPPED_IMAGE_PATH': 'path', 'FILENAME_VIEW': 'view'})
df_img['patient_id'] = df_img['external_id'].apply(lambda x: x.split('_')[0])
df_img = df_img[['patient_id', 'external_id', 'view', 'path']]
df_img

,patient_id,external_id,view,path
0,AN00001,AN00001_Y_VIEW_4,Y_VIEW_4,../data/cropped_images/AN00001_Y_VIEW_4.jpg
1,AN00010,AN00010__1001,_1001,../data/cropped_images/AN00010__1001.jpg
5,AN00100,AN00100_AXILLARY_4,AXILLARY_4,../data/cropped_images/AN00100_AXILLARY_4.jpg
6,AN00100,AN00100_EXT_ROTATION_1,EXT_ROTATION_1,../data/cropped_images/AN00100_EXT_ROTATION_1.jpg
7,AN00100,AN00100_INT_ROTATION_2,INT_ROTATION_2,../data/cropped_images/AN00100_INT_ROTATION_2.jpg
...,...,...,...,...
1111,AN00099,AN00099_Shoulder_R_2,Shoulder_R_2,../data/cropped_images/AN00099_Shoulder_R_2.jpg
1112,AN00099,AN00099_Shoulder_R_3,Shoulder_R_3,../data/cropped_images/AN00099_Shoulder_R_3.jpg
1113,AN00001,AN00001_AXILLARY_3,AXILLARY_3,../data/cropped_images/AN00001_AXILLARY_3.jpg
1114,AN00001,AN00001_EXT_ROTATION_2,EXT_ROTATION_2,../data/cropped_images/AN00001_EXT_ROTATION_2.jpg
1115,AN00001,AN00001_INT_ROTATION_1,INT_ROTATION_1,../data/cropped_images/AN00001_INT_ROTATION_1.jpg

### Record of misclassified studies
AN00017 has both images marked as AP-like unclear why

In [20]:
# standardize view names
df_img['view_std'] = None

# order matters here
patterns = dict(
    G = '.*GRAS.*$', # some mention G and AP. Put first to defer to G
    AP = '^(?!.*\_Y|AXIL|GRAS|LAT|SCAP).*AP.*$',  # some of the names mention both Y and AP
    H =  '^(?!.*AP|AXIL|GRAS|LAT).*HUMER.*$',
    TH = '^(?!.*AP|AXIL|LAT|GRAS|HUMER).*THORAC.*$',
    AX = '^(?!.*AP|HUMER|GRAS|LAT).*AXIL|AXIO.*$',
    Y = '^(?!.*AP|GRAS|AXIL|LAT).*Y.*$',  # Y is last because axillary and grashley both have "Y" in them. Check for false positives
)

for k, v in patterns.items():
    k_cond = df_img.view.str.contains(v, case=False)
    k_cond = k_cond & df_img.view_std.isna()
    df_img.loc[k_cond, 'view_std'] = k
   
    prev_cond = k_cond

# merge on sbf input
dfm = df_img.merge(df_sbf, how='left')

# code special cases from email "Standardized_view_name"
dfm.loc[dfm.view=='LAT_HUMERUS_2', 'view_std'] = 'Y'
dfm.loc[dfm.view=='HUMERUS_LAT_2', 'view_std'] = 'AP'
dfm.loc[dfm.view=='HUMERUS_LAT_3', 'view_std'] = 'AP'

# case 1: std_view is missing and std_view_sbf is not missing:
# action: use sbf
cond_1 = dfm.view_std.isna() & ~dfm.view_std_sbf.isna()
dfm.loc[cond_1, 'view_std'] = dfm.loc[cond_1, 'view_std_sbf']

# case 2: std_view is not missing and std_view_sbf is missing:
# no action taken since STD_VIEW already set appropriately

# case 3 a) both are non-missing and agree
# action: they agree so do nothing

# case 3 b) both are non-missing and they disagree
# action fix on a case-by case basis
cond_3b = (~dfm.view_std.isna() & ~dfm.view_std_sbf.isna()) & (dfm.view_std != dfm.view_std_sbf)
display(dfm.loc[cond_3b, ['view', 'view_std', 'view_std_sbf']])

# case 4: both are missing
# action: after cleaning, only those marked as ambiguous by SBF remain, so going to work with this.
cond_4 = (dfm.view_std.isna() & dfm.view_std_sbf.isna())
dfm.loc[cond_4, ['view', 'view_std', 'view_std_sbf']]

Empty DataFrame
Columns: [view, view_std, view_std_sbf]
Index: []

               view view_std view_std_sbf
17     Shoulder_L_4     None          NaN
21     Shoulder_L_4     None          NaN
47     Shoulder_R_4     None          NaN
75     Shoulder_R_4     None          NaN
136         AXIAL_3     None          NaN
147         AXIAL_3     None          NaN
193         AXIAL_3     None          NaN
227         AXIAL_3     None          NaN
231         AXIAL_3     None          NaN
262    Shoulder_L_4     None          NaN
271    Shoulder_R_4     None          NaN
277    Shoulder_L_4     None          NaN
279         AXIAL_3     None          NaN
284    Shoulder_L_4     None          NaN
294    Shoulder_L_4     None          NaN
317    Shoulder_R_4     None          NaN
332    Shoulder_L_4     None          NaN
339    Shoulder_L_4     None          NaN
388    Shoulder_R_4     None          NaN
400    Shoulder_R_4     None          NaN
407    Shoulder_L_4     None          NaN
541   Scapula_LAT_3     None          NaN
879    Shoulder_L_6     None          NaN
894    Shoulder_L_4     None          NaN
926    Shoulder_R_4     None          NaN
974    Shoulder_R_4     None          NaN
978    Shoulder_R_4     None          NaN
1017   Shoulder_R_4     None          NaN

In [21]:
# Add standardized view names to images
dfm = dfm.drop(['view', 'view_std_sbf', 'count'], axis=1)
df_img = dfm.rename(columns = {'view_std': 'view'})

In [22]:
# add high-level view names
group_view_mapping = {
    'AP': 'AP_LIKE',
    'H': 'AP_LIKE',
    'G': 'AP_LIKE',
    'TH': 'AP_LIKE',
    'Y': 'Y',
    'AX': 'AXIL',
}

df_img['view_group'] = df_img.view.map(group_view_mapping)
df_img

,patient_id,external_id,path,view,view_group
0,AN00001,AN00001_Y_VIEW_4,../data/cropped_images/AN00001_Y_VIEW_4.jpg,Y,Y
1,AN00010,AN00010__1001,../data/cropped_images/AN00010__1001.jpg,AP,AP_LIKE
2,AN00100,AN00100_AXILLARY_4,../data/cropped_images/AN00100_AXILLARY_4.jpg,AX,AXIL
3,AN00100,AN00100_EXT_ROTATION_1,../data/cropped_images/AN00100_EXT_ROTATION_1.jpg,AP,AP_LIKE
4,AN00100,AN00100_INT_ROTATION_2,../data/cropped_images/AN00100_INT_ROTATION_2.jpg,AP,AP_LIKE
...,...,...,...,...,...
1037,AN00099,AN00099_Shoulder_R_2,../data/cropped_images/AN00099_Shoulder_R_2.jpg,AP,AP_LIKE
1038,AN00099,AN00099_Shoulder_R_3,../data/cropped_images/AN00099_Shoulder_R_3.jpg,AP,AP_LIKE
1039,AN00001,AN00001_AXILLARY_3,../data/cropped_images/AN00001_AXILLARY_3.jpg,AX,AXIL
1040,AN00001,AN00001_EXT_ROTATION_2,../data/cropped_images/AN00001_EXT_ROTATION_2.jpg,AP,AP_LIKE
1041,AN00001,AN00001_INT_ROTATION_1,../data/cropped_images/AN00001_INT_ROTATION_1.jpg,AP,AP_LIKE

In [23]:
df_img.view.value_counts(dropna=False)

AP      808
Y       115
AX       34
H        31
None     28
G        25
TH        1
Name: view, dtype: int64

In [24]:
df_img.view_group.value_counts(dropna=False)

AP_LIKE    865
Y          115
AXIL        34
NaN         28
Name: view_group, dtype: int64

In [25]:
df_img.query('view_group=="AP_LIKE"').value_counts('view')

view
AP    808
H      31
G      25
TH      1
dtype: int64

In [26]:
# clean target data
df_trg = df_trg.rename(columns = {'AN_': 'patient_id', 'Num_parts': 'num_parts', 'Fracture_type': 'fracture_type'})
df_trg['patient_id'] = df_trg['patient_id'].apply(lambda x: f"AN{str(x).zfill(5)}")
df_trg

    patient_id  num_parts fracture_type
0      AN00001          1        1 part
1      AN00002          1        1 part
2      AN00003          4  3 and 4 part
3      AN00004          4  3 and 4 part
4      AN00005          1        1 part
..         ...        ...           ...
380    AN00381          1        1 part
381    AN00382          3  3 and 4 part
382    AN00383          1        1 part
383    AN00384          1        1 part
384    AN00385          2        2 part

[385 rows x 3 columns]

In [27]:
# save both sets
df_img.to_csv(model_img_data_path, index=None)
df_trg.to_csv(model_trg_data_path, index=None)

In [28]:
df_img.loc[df_img.external_id.str.contains('lat_humerus_2', case=False)]

,patient_id,external_id,path,view,view_group
366,AN00022,AN00022_LAT_HUMERUS_2,../data/cropped_images/AN00022_LAT_HUMERUS_2.jpg,Y,Y
451,AN00025,AN00025_LAT_HUMERUS_2,../data/cropped_images/AN00025_LAT_HUMERUS_2.jpg,Y,Y
834,AN00380,AN00380_LAT_HUMERUS_2,../data/cropped_images/AN00380_LAT_HUMERUS_2.jpg,Y,Y